### ISSUE TITLE
How to make NestedMocking with Different functions

### ISSUE THREAD

**Issue by kyohaifeng** [SvetlovA/static-mock#1]
How can  make NestedMocking with Different functions?
like this:
        public void TestNestedReturnMock()
        {
            const int expectedParentResult = 2;
            const int expectedChildResult = 3;

            Mock.Setup(() => TestStaticClass.TestMethodReturn1WithoutParameters(), () =>
            {
                Mock.Setup(() => TestStaticClass.TestMethodReturnWithParameter(5), () =>
                {
                    var actualParentResult = TestStaticClass.TestMethodReturn1WithoutParameters();
                    Assert.AreEqual(expectedParentResult, actualParentResult);
                    var actualChildResult = TestStaticClass.TestMethodReturnWithParameter(5);
                    Assert.AreEqual(expectedChildResult, actualChildResult);
                }).Returns(expectedChildResult);
            }).Returns(expectedParentResult);
        }

An exception occurred when I was testing
<img width="227" alt="error" src="https://user-images.githubusercontent.com/48502242/123071282-7f689f80-d44f-11eb-8ef7-f02ffea71a5f.PNG">

**Comment by SvetlovA** [comment]
Hello @kyohaifeng. I tried to reproduce your issue and it reproduced. I mark this issue as bug. But I found a workaround. The problem is that you call parent function from child scope. To solve it you need to move parent function calling to parent function scope and it will work for you. Like this:
```
        [Test]
        public void TestNestedReturnMockWithDifferentFunctions()
        {
            const int expectedParentResult = 2;
            const int expectedChildResult = 3;

            Mock.Setup(() => TestStaticClass.TestMethodReturn1WithoutParameters(), () =>
            {
                var actualParentResult = TestStaticClass.TestMethodReturn1WithoutParameters();
                Mock.Setup(() => TestStaticClass.TestMethodReturnWithParameter(2), () =>
                {
                    var actualChildResult = TestStaticClass.TestMethodReturnWithParameter(2);
                    Assert.AreEqual(expectedParentResult, actualParentResult);
                    Assert.AreEqual(expectedChildResult, actualChildResult);
                }).Returns(expectedChildResult);
            }).Returns(expectedParentResult);
        }
```

**Comment by kyohaifeng** [comment]
Hello,@SvetlovA .Thank you very much for your reply.how can call parent function from child scope ?
I hava a method like this, I want to mock the two methods in parent method, but it will happen error .
public int parentMethodA(int paramsB){
int resultA = TestStaticClass.TestMethodReturn1WithoutParameters();
int resultB =  TestStaticClass.TestMethodReturnWithParameter(paramsB);
return resultA + resultB;
}

[Test]
        public void TestParentMethodA()
        {
            const int expectedParentResult = 10;
　　　const int expectedChildAResult = 8;
           const int expectedChildBResult = 2;
　　　Mock.Setup(() => TestStaticClass.TestMethodReturn1WithoutParameters(), () =>
            {
                Mock.Setup(() => TestStaticClass.TestMethodReturnWithParameter(It.isAny<int>()), () =>
                {
                     int  actualParentResult = parentMethodA(20);
                    Assert.AreEqual(expectedParentResult , actualParentResult );
                }).Returns(expectedChildBResult);
            }).Returns(expectedChildAResult);
        }

**Comment by SvetlovA** [comment]
Sorry for so late answer, try to use **Callback** functionality. Like this:
```
        public static int parentMethodA(int paramsB)
        {
            int resultA = TestStaticClass.TestMethodReturn1WithoutParameters();
            int resultB = TestStaticClass.TestMethodReturnWithParameter(paramsB);
            return resultA + resultB;
        }

        [Test]
        public void TestParentMethodA()
        {
            const int expectedParentResult = 10;
            const int expectedChildAResult = 8;
            const int expectedChildBResult = 2;
            Mock.Setup(() => TestStaticClass.TestMethodReturn1WithoutParameters(), () =>
            {
                Mock.Setup(() => TestStaticClass.TestMethodReturnWithParameter(2), () =>
                {
                    int actualParentResult = parentMethodA(20);
                    Assert.AreEqual(expectedParentResult, actualParentResult);
                }).Callback(() => expectedChildBResult);
            }).Callback(() => expectedChildAResult);
        }
```

I will be back with fix of returns as soon as possible.

**Comment by kyohaifeng** [comment]
Hi, @SvetlovA .I am glad to have your reply.
I also have two question for your help
First like this :
public static int parentMethodA()
        {
            int resultA = TestStaticClass.TestMethodReturn1WithoutParameters();
            TestStaticClass.TestMethodNoReturnWithoutParameter();
            return resultA ;
        }

        [Test]
        public void TestParentMethodA()
        {
            const int expectedResult = 8;
            Mock.Setup(() => TestStaticClass.TestMethodReturn1WithoutParameters(), () =>
            {
                    int actualResult = parentMethodA();
                    Assert.AreEqual(expectedResult , actualResult );
            }).Callback(() => expectedResult );
        }

Seconde Like this:

public static int parentMethod()
        {
         TestClassA  objectA = new TestClassA();
            int result = objectA .TestMethodReturn1WithoutParameters();
            return result ;
        }

        [Test]
        public void TestParentMethod()
        {
            const int expectedResult = 8;
            Mock.Setup(Typeof(TestClassA  ),nameOf( TestClassA .TestMethodReturn1WithoutParameters), () =>
            {
                    int actualResult = parentMethod();
                    Assert.AreEqual(expectedResult , actualResult );
            }).Returns( expectedResult );
        }

All tests have the same exception as above.
I am a beginner C#, sorry to ask you too many questions

**Comment by SvetlovA** [comment]
I released new version of this lib [SMock(1.3.0)](https://www.nuget.org/packages/SMock/1.3.0). Try to update lib and run your tests again. We have one known issue:
* **System.AccessViolationException:** This exception most often occurs if you use x64 platform in your test project. If you have this exception **System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'** try to move mocking methods away from each other or try to use x32 platform for your test project compilation.

If it doesn't help reopen this issue and I try to fix it as far as possible.
Feel free to ask any other questions.

**Comment by kyohaifeng** [comment]
Hello, thank you very much for your update. I read your code, but I still can't understand hook. I'll test it tomorrow. This is too hard for me.

**Comment by SvetlovA** [comment]
To understand hooks I read this http://kylehalladay.com/blog/2020/11/13/Hooking-By-Example.html article. I put link here, maybe it helps you to understand it better.

**Comment by kyohaifeng** [comment]
Hi,I tested it on a 32-bit platform, and the test result is OK. Thank you very much for your links to hooks. I'll read it well
